// export by github.com/goplus/ixgo/cmd/qexp

package mcp

import (
	q "github.com/mark3labs/mcp-go/mcp"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("github.com/mark3labs/mcp-go/mcp", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "mcp",
			Path: "github.com/mark3labs/mcp-go/mcp",
			Deps: map[string]string{
				"context":                            "context",
				"encoding/json":                      "json",
				"errors":                             "errors",
				"fmt":                                "fmt",
				"github.com/invopop/jsonschema":      "jsonschema",
				"github.com/spf13/cast":              "cast",
				"github.com/yosida95/uritemplate/v3": "uritemplate",
				"maps":                               "maps",
				"net/http":                           "http",
				"reflect":                            "reflect",
				"strconv":                            "strconv",
			},
			Interfaces: map[string]reflect.Type{
				"ClientNotification": reflect.TypeOf((*q.ClientNotification)(nil)).Elem(),
				"ClientRequest":      reflect.TypeOf((*q.ClientRequest)(nil)).Elem(),
				"ClientResult":       reflect.TypeOf((*q.ClientResult)(nil)).Elem(),
				"Content":            reflect.TypeOf((*q.Content)(nil)).Elem(),
				"JSONRPCMessage":     reflect.TypeOf((*q.JSONRPCMessage)(nil)).Elem(),
				"Named":              reflect.TypeOf((*q.Named)(nil)).Elem(),
				"ProgressToken":      reflect.TypeOf((*q.ProgressToken)(nil)).Elem(),
				"ResourceContents":   reflect.TypeOf((*q.ResourceContents)(nil)).Elem(),
				"ServerNotification": reflect.TypeOf((*q.ServerNotification)(nil)).Elem(),
				"ServerRequest":      reflect.TypeOf((*q.ServerRequest)(nil)).Elem(),
				"ServerResult":       reflect.TypeOf((*q.ServerResult)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Annotated":                         reflect.TypeOf((*q.Annotated)(nil)).Elem(),
				"Annotations":                       reflect.TypeOf((*q.Annotations)(nil)).Elem(),
				"ArgumentOption":                    reflect.TypeOf((*q.ArgumentOption)(nil)).Elem(),
				"AudioContent":                      reflect.TypeOf((*q.AudioContent)(nil)).Elem(),
				"BlobResourceContents":              reflect.TypeOf((*q.BlobResourceContents)(nil)).Elem(),
				"CallToolParams":                    reflect.TypeOf((*q.CallToolParams)(nil)).Elem(),
				"CallToolRequest":                   reflect.TypeOf((*q.CallToolRequest)(nil)).Elem(),
				"CallToolResult":                    reflect.TypeOf((*q.CallToolResult)(nil)).Elem(),
				"CancelledNotification":             reflect.TypeOf((*q.CancelledNotification)(nil)).Elem(),
				"CancelledNotificationParams":       reflect.TypeOf((*q.CancelledNotificationParams)(nil)).Elem(),
				"ClientCapabilities":                reflect.TypeOf((*q.ClientCapabilities)(nil)).Elem(),
				"CompleteParams":                    reflect.TypeOf((*q.CompleteParams)(nil)).Elem(),
				"CompleteRequest":                   reflect.TypeOf((*q.CompleteRequest)(nil)).Elem(),
				"CompleteResult":                    reflect.TypeOf((*q.CompleteResult)(nil)).Elem(),
				"CreateMessageParams":               reflect.TypeOf((*q.CreateMessageParams)(nil)).Elem(),
				"CreateMessageRequest":              reflect.TypeOf((*q.CreateMessageRequest)(nil)).Elem(),
				"CreateMessageResult":               reflect.TypeOf((*q.CreateMessageResult)(nil)).Elem(),
				"Cursor":                            reflect.TypeOf((*q.Cursor)(nil)).Elem(),
				"ElicitationParams":                 reflect.TypeOf((*q.ElicitationParams)(nil)).Elem(),
				"ElicitationRequest":                reflect.TypeOf((*q.ElicitationRequest)(nil)).Elem(),
				"ElicitationResponse":               reflect.TypeOf((*q.ElicitationResponse)(nil)).Elem(),
				"ElicitationResponseAction":         reflect.TypeOf((*q.ElicitationResponseAction)(nil)).Elem(),
				"ElicitationResult":                 reflect.TypeOf((*q.ElicitationResult)(nil)).Elem(),
				"EmbeddedResource":                  reflect.TypeOf((*q.EmbeddedResource)(nil)).Elem(),
				"EmptyResult":                       reflect.TypeOf((*q.EmptyResult)(nil)).Elem(),
				"GetPromptParams":                   reflect.TypeOf((*q.GetPromptParams)(nil)).Elem(),
				"GetPromptRequest":                  reflect.TypeOf((*q.GetPromptRequest)(nil)).Elem(),
				"GetPromptResult":                   reflect.TypeOf((*q.GetPromptResult)(nil)).Elem(),
				"ImageContent":                      reflect.TypeOf((*q.ImageContent)(nil)).Elem(),
				"Implementation":                    reflect.TypeOf((*q.Implementation)(nil)).Elem(),
				"InitializeParams":                  reflect.TypeOf((*q.InitializeParams)(nil)).Elem(),
				"InitializeRequest":                 reflect.TypeOf((*q.InitializeRequest)(nil)).Elem(),
				"InitializeResult":                  reflect.TypeOf((*q.InitializeResult)(nil)).Elem(),
				"InitializedNotification":           reflect.TypeOf((*q.InitializedNotification)(nil)).Elem(),
				"JSONRPCError":                      reflect.TypeOf((*q.JSONRPCError)(nil)).Elem(),
				"JSONRPCErrorDetails":               reflect.TypeOf((*q.JSONRPCErrorDetails)(nil)).Elem(),
				"JSONRPCNotification":               reflect.TypeOf((*q.JSONRPCNotification)(nil)).Elem(),
				"JSONRPCRequest":                    reflect.TypeOf((*q.JSONRPCRequest)(nil)).Elem(),
				"JSONRPCResponse":                   reflect.TypeOf((*q.JSONRPCResponse)(nil)).Elem(),
				"ListPromptsRequest":                reflect.TypeOf((*q.ListPromptsRequest)(nil)).Elem(),
				"ListPromptsResult":                 reflect.TypeOf((*q.ListPromptsResult)(nil)).Elem(),
				"ListResourceTemplatesRequest":      reflect.TypeOf((*q.ListResourceTemplatesRequest)(nil)).Elem(),
				"ListResourceTemplatesResult":       reflect.TypeOf((*q.ListResourceTemplatesResult)(nil)).Elem(),
				"ListResourcesRequest":              reflect.TypeOf((*q.ListResourcesRequest)(nil)).Elem(),
				"ListResourcesResult":               reflect.TypeOf((*q.ListResourcesResult)(nil)).Elem(),
				"ListRootsRequest":                  reflect.TypeOf((*q.ListRootsRequest)(nil)).Elem(),
				"ListRootsResult":                   reflect.TypeOf((*q.ListRootsResult)(nil)).Elem(),
				"ListToolsRequest":                  reflect.TypeOf((*q.ListToolsRequest)(nil)).Elem(),
				"ListToolsResult":                   reflect.TypeOf((*q.ListToolsResult)(nil)).Elem(),
				"LoggingLevel":                      reflect.TypeOf((*q.LoggingLevel)(nil)).Elem(),
				"LoggingMessageNotification":        reflect.TypeOf((*q.LoggingMessageNotification)(nil)).Elem(),
				"LoggingMessageNotificationParams":  reflect.TypeOf((*q.LoggingMessageNotificationParams)(nil)).Elem(),
				"MCPMethod":                         reflect.TypeOf((*q.MCPMethod)(nil)).Elem(),
				"Meta":                              reflect.TypeOf((*q.Meta)(nil)).Elem(),
				"ModelHint":                         reflect.TypeOf((*q.ModelHint)(nil)).Elem(),
				"ModelPreferences":                  reflect.TypeOf((*q.ModelPreferences)(nil)).Elem(),
				"Notification":                      reflect.TypeOf((*q.Notification)(nil)).Elem(),
				"NotificationParams":                reflect.TypeOf((*q.NotificationParams)(nil)).Elem(),
				"PaginatedParams":                   reflect.TypeOf((*q.PaginatedParams)(nil)).Elem(),
				"PaginatedRequest":                  reflect.TypeOf((*q.PaginatedRequest)(nil)).Elem(),
				"PaginatedResult":                   reflect.TypeOf((*q.PaginatedResult)(nil)).Elem(),
				"Params":                            reflect.TypeOf((*q.Params)(nil)).Elem(),
				"PingRequest":                       reflect.TypeOf((*q.PingRequest)(nil)).Elem(),
				"ProgressNotification":              reflect.TypeOf((*q.ProgressNotification)(nil)).Elem(),
				"ProgressNotificationParams":        reflect.TypeOf((*q.ProgressNotificationParams)(nil)).Elem(),
				"Prompt":                            reflect.TypeOf((*q.Prompt)(nil)).Elem(),
				"PromptArgument":                    reflect.TypeOf((*q.PromptArgument)(nil)).Elem(),
				"PromptListChangedNotification":     reflect.TypeOf((*q.PromptListChangedNotification)(nil)).Elem(),
				"PromptMessage":                     reflect.TypeOf((*q.PromptMessage)(nil)).Elem(),
				"PromptOption":                      reflect.TypeOf((*q.PromptOption)(nil)).Elem(),
				"PromptReference":                   reflect.TypeOf((*q.PromptReference)(nil)).Elem(),
				"PropertyOption":                    reflect.TypeOf((*q.PropertyOption)(nil)).Elem(),
				"ReadResourceParams":                reflect.TypeOf((*q.ReadResourceParams)(nil)).Elem(),
				"ReadResourceRequest":               reflect.TypeOf((*q.ReadResourceRequest)(nil)).Elem(),
				"ReadResourceResult":                reflect.TypeOf((*q.ReadResourceResult)(nil)).Elem(),
				"Request":                           reflect.TypeOf((*q.Request)(nil)).Elem(),
				"RequestId":                         reflect.TypeOf((*q.RequestId)(nil)).Elem(),
				"RequestParams":                     reflect.TypeOf((*q.RequestParams)(nil)).Elem(),
				"Resource":                          reflect.TypeOf((*q.Resource)(nil)).Elem(),
				"ResourceLink":                      reflect.TypeOf((*q.ResourceLink)(nil)).Elem(),
				"ResourceListChangedNotification":   reflect.TypeOf((*q.ResourceListChangedNotification)(nil)).Elem(),
				"ResourceOption":                    reflect.TypeOf((*q.ResourceOption)(nil)).Elem(),
				"ResourceReference":                 reflect.TypeOf((*q.ResourceReference)(nil)).Elem(),
				"ResourceTemplate":                  reflect.TypeOf((*q.ResourceTemplate)(nil)).Elem(),
				"ResourceTemplateOption":            reflect.TypeOf((*q.ResourceTemplateOption)(nil)).Elem(),
				"ResourceUpdatedNotification":       reflect.TypeOf((*q.ResourceUpdatedNotification)(nil)).Elem(),
				"ResourceUpdatedNotificationParams": reflect.TypeOf((*q.ResourceUpdatedNotificationParams)(nil)).Elem(),
				"Result":                            reflect.TypeOf((*q.Result)(nil)).Elem(),
				"Role":                              reflect.TypeOf((*q.Role)(nil)).Elem(),
				"Root":                              reflect.TypeOf((*q.Root)(nil)).Elem(),
				"RootsListChangedNotification":      reflect.TypeOf((*q.RootsListChangedNotification)(nil)).Elem(),
				"SamplingMessage":                   reflect.TypeOf((*q.SamplingMessage)(nil)).Elem(),
				"ServerCapabilities":                reflect.TypeOf((*q.ServerCapabilities)(nil)).Elem(),
				"SetLevelParams":                    reflect.TypeOf((*q.SetLevelParams)(nil)).Elem(),
				"SetLevelRequest":                   reflect.TypeOf((*q.SetLevelRequest)(nil)).Elem(),
				"SubscribeParams":                   reflect.TypeOf((*q.SubscribeParams)(nil)).Elem(),
				"SubscribeRequest":                  reflect.TypeOf((*q.SubscribeRequest)(nil)).Elem(),
				"TextContent":                       reflect.TypeOf((*q.TextContent)(nil)).Elem(),
				"TextResourceContents":              reflect.TypeOf((*q.TextResourceContents)(nil)).Elem(),
				"Tool":                              reflect.TypeOf((*q.Tool)(nil)).Elem(),
				"ToolAnnotation":                    reflect.TypeOf((*q.ToolAnnotation)(nil)).Elem(),
				"ToolArgumentsSchema":               reflect.TypeOf((*q.ToolArgumentsSchema)(nil)).Elem(),
				"ToolInputSchema":                   reflect.TypeOf((*q.ToolInputSchema)(nil)).Elem(),
				"ToolListChangedNotification":       reflect.TypeOf((*q.ToolListChangedNotification)(nil)).Elem(),
				"ToolOption":                        reflect.TypeOf((*q.ToolOption)(nil)).Elem(),
				"ToolOutputSchema":                  reflect.TypeOf((*q.ToolOutputSchema)(nil)).Elem(),
				"URITemplate":                       reflect.TypeOf((*q.URITemplate)(nil)).Elem(),
				"UnsubscribeParams":                 reflect.TypeOf((*q.UnsubscribeParams)(nil)).Elem(),
				"UnsubscribeRequest":                reflect.TypeOf((*q.UnsubscribeRequest)(nil)).Elem(),
				"UnsupportedProtocolVersionError":   reflect.TypeOf((*q.UnsupportedProtocolVersionError)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"ErrInternalError":      reflect.ValueOf(&q.ErrInternalError),
				"ErrInvalidParams":      reflect.ValueOf(&q.ErrInvalidParams),
				"ErrInvalidRequest":     reflect.ValueOf(&q.ErrInvalidRequest),
				"ErrMethodNotFound":     reflect.ValueOf(&q.ErrMethodNotFound),
				"ErrParseError":         reflect.ValueOf(&q.ErrParseError),
				"ErrRequestInterrupted": reflect.ValueOf(&q.ErrRequestInterrupted),
				"ErrResourceNotFound":   reflect.ValueOf(&q.ErrResourceNotFound),
				"ValidProtocolVersions": reflect.ValueOf(&q.ValidProtocolVersions),
			},
			Funcs: map[string]reflect.Value{
				"AdditionalProperties":           reflect.ValueOf(q.AdditionalProperties),
				"ArgumentDescription":            reflect.ValueOf(q.ArgumentDescription),
				"AsAudioContent":                 reflect.ValueOf(q.AsAudioContent),
				"AsBlobResourceContents":         reflect.ValueOf(q.AsBlobResourceContents),
				"AsEmbeddedResource":             reflect.ValueOf(q.AsEmbeddedResource),
				"AsImageContent":                 reflect.ValueOf(q.AsImageContent),
				"AsTextContent":                  reflect.ValueOf(q.AsTextContent),
				"AsTextResourceContents":         reflect.ValueOf(q.AsTextResourceContents),
				"DefaultBool":                    reflect.ValueOf(q.DefaultBool),
				"DefaultNumber":                  reflect.ValueOf(q.DefaultNumber),
				"DefaultString":                  reflect.ValueOf(q.DefaultString),
				"Description":                    reflect.ValueOf(q.Description),
				"Enum":                           reflect.ValueOf(q.Enum),
				"ExtractMap":                     reflect.ValueOf(q.ExtractMap),
				"ExtractString":                  reflect.ValueOf(q.ExtractString),
				"FormatNumberResult":             reflect.ValueOf(q.FormatNumberResult),
				"GetTextFromContent":             reflect.ValueOf(q.GetTextFromContent),
				"IsUnsupportedProtocolVersion":   reflect.ValueOf(q.IsUnsupportedProtocolVersion),
				"Items":                          reflect.ValueOf(q.Items),
				"MarshalContent":                 reflect.ValueOf(q.MarshalContent),
				"Max":                            reflect.ValueOf(q.Max),
				"MaxItems":                       reflect.ValueOf(q.MaxItems),
				"MaxLength":                      reflect.ValueOf(q.MaxLength),
				"MaxProperties":                  reflect.ValueOf(q.MaxProperties),
				"Min":                            reflect.ValueOf(q.Min),
				"MinItems":                       reflect.ValueOf(q.MinItems),
				"MinLength":                      reflect.ValueOf(q.MinLength),
				"MinProperties":                  reflect.ValueOf(q.MinProperties),
				"MultipleOf":                     reflect.ValueOf(q.MultipleOf),
				"NewAudioContent":                reflect.ValueOf(q.NewAudioContent),
				"NewEmbeddedResource":            reflect.ValueOf(q.NewEmbeddedResource),
				"NewGetPromptResult":             reflect.ValueOf(q.NewGetPromptResult),
				"NewImageContent":                reflect.ValueOf(q.NewImageContent),
				"NewInitializeResult":            reflect.ValueOf(q.NewInitializeResult),
				"NewJSONRPCError":                reflect.ValueOf(q.NewJSONRPCError),
				"NewJSONRPCErrorDetails":         reflect.ValueOf(q.NewJSONRPCErrorDetails),
				"NewJSONRPCResponse":             reflect.ValueOf(q.NewJSONRPCResponse),
				"NewJSONRPCResultResponse":       reflect.ValueOf(q.NewJSONRPCResultResponse),
				"NewListPromptsResult":           reflect.ValueOf(q.NewListPromptsResult),
				"NewListResourceTemplatesResult": reflect.ValueOf(q.NewListResourceTemplatesResult),
				"NewListResourcesResult":         reflect.ValueOf(q.NewListResourcesResult),
				"NewListToolsResult":             reflect.ValueOf(q.NewListToolsResult),
				"NewLoggingMessageNotification":  reflect.ValueOf(q.NewLoggingMessageNotification),
				"NewMetaFromMap":                 reflect.ValueOf(q.NewMetaFromMap),
				"NewProgressNotification":        reflect.ValueOf(q.NewProgressNotification),
				"NewPrompt":                      reflect.ValueOf(q.NewPrompt),
				"NewPromptMessage":               reflect.ValueOf(q.NewPromptMessage),
				"NewReadResourceResult":          reflect.ValueOf(q.NewReadResourceResult),
				"NewRequestId":                   reflect.ValueOf(q.NewRequestId),
				"NewResource":                    reflect.ValueOf(q.NewResource),
				"NewResourceLink":                reflect.ValueOf(q.NewResourceLink),
				"NewResourceTemplate":            reflect.ValueOf(q.NewResourceTemplate),
				"NewTextContent":                 reflect.ValueOf(q.NewTextContent),
				"NewTool":                        reflect.ValueOf(q.NewTool),
				"NewToolResultAudio":             reflect.ValueOf(q.NewToolResultAudio),
				"NewToolResultError":             reflect.ValueOf(q.NewToolResultError),
				"NewToolResultErrorFromErr":      reflect.ValueOf(q.NewToolResultErrorFromErr),
				"NewToolResultErrorf":            reflect.ValueOf(q.NewToolResultErrorf),
				"NewToolResultImage":             reflect.ValueOf(q.NewToolResultImage),
				"NewToolResultResource":          reflect.ValueOf(q.NewToolResultResource),
				"NewToolResultStructured":        reflect.ValueOf(q.NewToolResultStructured),
				"NewToolResultStructuredOnly":    reflect.ValueOf(q.NewToolResultStructuredOnly),
				"NewToolResultText":              reflect.ValueOf(q.NewToolResultText),
				"NewToolWithRawSchema":           reflect.ValueOf(q.NewToolWithRawSchema),
				"ParseAnnotations":               reflect.ValueOf(q.ParseAnnotations),
				"ParseArgument":                  reflect.ValueOf(q.ParseArgument),
				"ParseBoolean":                   reflect.ValueOf(q.ParseBoolean),
				"ParseCallToolResult":            reflect.ValueOf(q.ParseCallToolResult),
				"ParseContent":                   reflect.ValueOf(q.ParseContent),
				"ParseFloat32":                   reflect.ValueOf(q.ParseFloat32),
				"ParseFloat64":                   reflect.ValueOf(q.ParseFloat64),
				"ParseGetPromptResult":           reflect.ValueOf(q.ParseGetPromptResult),
				"ParseInt":                       reflect.ValueOf(q.ParseInt),
				"ParseInt16":                     reflect.ValueOf(q.ParseInt16),
				"ParseInt32":                     reflect.ValueOf(q.ParseInt32),
				"ParseInt64":                     reflect.ValueOf(q.ParseInt64),
				"ParseInt8":                      reflect.ValueOf(q.ParseInt8),
				"ParseReadResourceResult":        reflect.ValueOf(q.ParseReadResourceResult),
				"ParseResourceContents":          reflect.ValueOf(q.ParseResourceContents),
				"ParseString":                    reflect.ValueOf(q.ParseString),
				"ParseStringMap":                 reflect.ValueOf(q.ParseStringMap),
				"ParseUInt":                      reflect.ValueOf(q.ParseUInt),
				"ParseUInt16":                    reflect.ValueOf(q.ParseUInt16),
				"ParseUInt32":                    reflect.ValueOf(q.ParseUInt32),
				"ParseUInt64":                    reflect.ValueOf(q.ParseUInt64),
				"ParseUInt8":                     reflect.ValueOf(q.ParseUInt8),
				"Pattern":                        reflect.ValueOf(q.Pattern),
				"Properties":                     reflect.ValueOf(q.Properties),
				"PropertyNames":                  reflect.ValueOf(q.PropertyNames),
				"Required":                       reflect.ValueOf(q.Required),
				"RequiredArgument":               reflect.ValueOf(q.RequiredArgument),
				"Title":                          reflect.ValueOf(q.Title),
				"ToBoolPtr":                      reflect.ValueOf(q.ToBoolPtr),
				"UniqueItems":                    reflect.ValueOf(q.UniqueItems),
				"UnmarshalContent":               reflect.ValueOf(q.UnmarshalContent),
				"WithAnnotations":                reflect.ValueOf(q.WithAnnotations),
				"WithAny":                        reflect.ValueOf(q.WithAny),
				"WithArgument":                   reflect.ValueOf(q.WithArgument),
				"WithArray":                      reflect.ValueOf(q.WithArray),
				"WithBoolean":                    reflect.ValueOf(q.WithBoolean),
				"WithBooleanItems":               reflect.ValueOf(q.WithBooleanItems),
				"WithDescription":                reflect.ValueOf(q.WithDescription),
				"WithDestructiveHintAnnotation":  reflect.ValueOf(q.WithDestructiveHintAnnotation),
				"WithIdempotentHintAnnotation":   reflect.ValueOf(q.WithIdempotentHintAnnotation),
				"WithMIMEType":                   reflect.ValueOf(q.WithMIMEType),
				"WithNumber":                     reflect.ValueOf(q.WithNumber),
				"WithNumberItems":                reflect.ValueOf(q.WithNumberItems),
				"WithObject":                     reflect.ValueOf(q.WithObject),
				"WithOpenWorldHintAnnotation":    reflect.ValueOf(q.WithOpenWorldHintAnnotation),
				"WithPromptDescription":          reflect.ValueOf(q.WithPromptDescription),
				"WithRawInputSchema":             reflect.ValueOf(q.WithRawInputSchema),
				"WithRawOutputSchema":            reflect.ValueOf(q.WithRawOutputSchema),
				"WithReadOnlyHintAnnotation":     reflect.ValueOf(q.WithReadOnlyHintAnnotation),
				"WithResourceDescription":        reflect.ValueOf(q.WithResourceDescription),
				"WithString":                     reflect.ValueOf(q.WithString),
				"WithStringEnumItems":            reflect.ValueOf(q.WithStringEnumItems),
				"WithStringItems":                reflect.ValueOf(q.WithStringItems),
				"WithTemplateAnnotations":        reflect.ValueOf(q.WithTemplateAnnotations),
				"WithTemplateDescription":        reflect.ValueOf(q.WithTemplateDescription),
				"WithTemplateMIMEType":           reflect.ValueOf(q.WithTemplateMIMEType),
				"WithTitleAnnotation":            reflect.ValueOf(q.WithTitleAnnotation),
				"WithToolAnnotation":             reflect.ValueOf(q.WithToolAnnotation),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"ElicitationResponseActionAccept":  {Typ: reflect.TypeOf(q.ElicitationResponseActionAccept), Value: constant.MakeString(string(q.ElicitationResponseActionAccept))},
				"ElicitationResponseActionCancel":  {Typ: reflect.TypeOf(q.ElicitationResponseActionCancel), Value: constant.MakeString(string(q.ElicitationResponseActionCancel))},
				"ElicitationResponseActionDecline": {Typ: reflect.TypeOf(q.ElicitationResponseActionDecline), Value: constant.MakeString(string(q.ElicitationResponseActionDecline))},
				"LoggingLevelAlert":                {Typ: reflect.TypeOf(q.LoggingLevelAlert), Value: constant.MakeString(string(q.LoggingLevelAlert))},
				"LoggingLevelCritical":             {Typ: reflect.TypeOf(q.LoggingLevelCritical), Value: constant.MakeString(string(q.LoggingLevelCritical))},
				"LoggingLevelDebug":                {Typ: reflect.TypeOf(q.LoggingLevelDebug), Value: constant.MakeString(string(q.LoggingLevelDebug))},
				"LoggingLevelEmergency":            {Typ: reflect.TypeOf(q.LoggingLevelEmergency), Value: constant.MakeString(string(q.LoggingLevelEmergency))},
				"LoggingLevelError":                {Typ: reflect.TypeOf(q.LoggingLevelError), Value: constant.MakeString(string(q.LoggingLevelError))},
				"LoggingLevelInfo":                 {Typ: reflect.TypeOf(q.LoggingLevelInfo), Value: constant.MakeString(string(q.LoggingLevelInfo))},
				"LoggingLevelNotice":               {Typ: reflect.TypeOf(q.LoggingLevelNotice), Value: constant.MakeString(string(q.LoggingLevelNotice))},
				"LoggingLevelWarning":              {Typ: reflect.TypeOf(q.LoggingLevelWarning), Value: constant.MakeString(string(q.LoggingLevelWarning))},
				"MethodElicitationCreate":          {Typ: reflect.TypeOf(q.MethodElicitationCreate), Value: constant.MakeString(string(q.MethodElicitationCreate))},
				"MethodInitialize":                 {Typ: reflect.TypeOf(q.MethodInitialize), Value: constant.MakeString(string(q.MethodInitialize))},
				"MethodListRoots":                  {Typ: reflect.TypeOf(q.MethodListRoots), Value: constant.MakeString(string(q.MethodListRoots))},
				"MethodPing":                       {Typ: reflect.TypeOf(q.MethodPing), Value: constant.MakeString(string(q.MethodPing))},
				"MethodPromptsGet":                 {Typ: reflect.TypeOf(q.MethodPromptsGet), Value: constant.MakeString(string(q.MethodPromptsGet))},
				"MethodPromptsList":                {Typ: reflect.TypeOf(q.MethodPromptsList), Value: constant.MakeString(string(q.MethodPromptsList))},
				"MethodResourcesList":              {Typ: reflect.TypeOf(q.MethodResourcesList), Value: constant.MakeString(string(q.MethodResourcesList))},
				"MethodResourcesRead":              {Typ: reflect.TypeOf(q.MethodResourcesRead), Value: constant.MakeString(string(q.MethodResourcesRead))},
				"MethodResourcesTemplatesList":     {Typ: reflect.TypeOf(q.MethodResourcesTemplatesList), Value: constant.MakeString(string(q.MethodResourcesTemplatesList))},
				"MethodSamplingCreateMessage":      {Typ: reflect.TypeOf(q.MethodSamplingCreateMessage), Value: constant.MakeString(string(q.MethodSamplingCreateMessage))},
				"MethodSetLogLevel":                {Typ: reflect.TypeOf(q.MethodSetLogLevel), Value: constant.MakeString(string(q.MethodSetLogLevel))},
				"MethodToolsCall":                  {Typ: reflect.TypeOf(q.MethodToolsCall), Value: constant.MakeString(string(q.MethodToolsCall))},
				"MethodToolsList":                  {Typ: reflect.TypeOf(q.MethodToolsList), Value: constant.MakeString(string(q.MethodToolsList))},
				"RoleAssistant":                    {Typ: reflect.TypeOf(q.RoleAssistant), Value: constant.MakeString(string(q.RoleAssistant))},
				"RoleUser":                         {Typ: reflect.TypeOf(q.RoleUser), Value: constant.MakeString(string(q.RoleUser))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"ContentTypeAudio":                       {Typ: "untyped string", Value: constant.MakeString(string(q.ContentTypeAudio))},
				"ContentTypeImage":                       {Typ: "untyped string", Value: constant.MakeString(string(q.ContentTypeImage))},
				"ContentTypeLink":                        {Typ: "untyped string", Value: constant.MakeString(string(q.ContentTypeLink))},
				"ContentTypeResource":                    {Typ: "untyped string", Value: constant.MakeString(string(q.ContentTypeResource))},
				"ContentTypeText":                        {Typ: "untyped string", Value: constant.MakeString(string(q.ContentTypeText))},
				"INTERNAL_ERROR":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.INTERNAL_ERROR))},
				"INVALID_PARAMS":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.INVALID_PARAMS))},
				"INVALID_REQUEST":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.INVALID_REQUEST))},
				"JSONRPC_VERSION":                        {Typ: "untyped string", Value: constant.MakeString(string(q.JSONRPC_VERSION))},
				"LATEST_PROTOCOL_VERSION":                {Typ: "untyped string", Value: constant.MakeString(string(q.LATEST_PROTOCOL_VERSION))},
				"METHOD_NOT_FOUND":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.METHOD_NOT_FOUND))},
				"MethodNotificationPromptsListChanged":   {Typ: "untyped string", Value: constant.MakeString(string(q.MethodNotificationPromptsListChanged))},
				"MethodNotificationResourceUpdated":      {Typ: "untyped string", Value: constant.MakeString(string(q.MethodNotificationResourceUpdated))},
				"MethodNotificationResourcesListChanged": {Typ: "untyped string", Value: constant.MakeString(string(q.MethodNotificationResourcesListChanged))},
				"MethodNotificationRootsListChanged":     {Typ: "untyped string", Value: constant.MakeString(string(q.MethodNotificationRootsListChanged))},
				"MethodNotificationToolsListChanged":     {Typ: "untyped string", Value: constant.MakeString(string(q.MethodNotificationToolsListChanged))},
				"PARSE_ERROR":                            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.PARSE_ERROR))},
				"REQUEST_INTERRUPTED":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.REQUEST_INTERRUPTED))},
				"RESOURCE_NOT_FOUND":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RESOURCE_NOT_FOUND))},
			},
		}
	})
}
